pid_file /run/mosquitto/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

allow_anonymous false
password_file /etc/mosquitto/passwd

listener 8883
cafile /etc/mosquitto/server.crt
certfile /etc/mosquitto/server.crt
keyfile /etc/mosquitto/server.key

acl_file /etc/mosquitto/aclfile
